ALTER TYPE "RegStatus" RENAME VALUE 'ACCEPTED' TO 'ACTIVE_MEMBER';
ALTER TYPE "RegStatus" ADD VALUE IF NOT EXISTS 'INCOMPLETE';
ALTER TYPE "RegStatus" ADD VALUE IF NOT EXISTS 'CONTACTED';
ALTER TYPE "RegStatus" ADD VALUE IF NOT EXISTS 'VERIFIED';
ALTER TYPE "RegStatus" ADD VALUE IF NOT EXISTS 'PRABUMI_PARTICIPANT';
ALTER TYPE "RegStatus" ADD VALUE IF NOT EXISTS 'PASSED';
ALTER TYPE "RegStatus" ADD VALUE IF NOT EXISTS 'INACTIVE';
ALTER TYPE "RegStatus" ADD VALUE IF NOT EXISTS 'ALUMNI';

ALTER TYPE "MemberStatus" RENAME VALUE 'ACTIVE' TO 'ACTIVE_MEMBER';

ALTER TABLE "registrations"
  ADD COLUMN IF NOT EXISTS "email" TEXT,
  ADD COLUMN IF NOT EXISTS "entry_year" INTEGER,
  ADD COLUMN IF NOT EXISTS "district" TEXT,
  ADD COLUMN IF NOT EXISTS "village" TEXT,
  ADD COLUMN IF NOT EXISTS "organization_experience" TEXT,
  ADD COLUMN IF NOT EXISTS "interests" TEXT,
  ADD COLUMN IF NOT EXISTS "consent_at" TIMESTAMP(3);
