/**
 * Daftar administratif Kabupaten Indramayu dari Pemerintah Kabupaten Indramayu.
 * Data diperiksa pada 21 September 2026.
 */
export const indramayuRegions = {
  "Haurgeulis": [
    "Haurkolot",
    "Haurgeulis",
    "Sukajati",
    "Wanakaya",
    "Karangtumaritis",
    "Kertanegara",
    "Cipancuh",
    "Mekarjati",
    "Sidadadi",
    "Sumbermulya"
  ],
  "Gantar": [
    "Bantarwaru",
    "Sanca",
    "Mekarjaya",
    "Gantar",
    "Situraja",
    "Baleraja",
    "Mekarwaru"
  ],
  "Kroya": [
    "Sukaslamet",
    "Tanjungkerta",
    "Kroya",
    "Sumbon",
    "Sukamelang",
    "Temiyang",
    "Temiyangsari",
    "Jayamulya",
    "Sumberjaya"
  ],
  "Gabuswetan": [
    "Kedungdawa",
    "Babakanjaya",
    "Gabuskulon",
    "Sekarmulya",
    "Kedokangabus",
    "Rancamulya",
    "Rancahan",
    "Gabuswetan",
    "Drunten Wetan",
    "Drunten Kulon"
  ],
  "Cikedung": [
    "Loyang",
    "Amis",
    "Jatisura",
    "Jambak",
    "Cikedung",
    "Cikedung Lor",
    "Mundakjaya"
  ],
  "Terisi": [
    "Cikawung",
    "Jatimunggul",
    "Jatimulya",
    "Plosokerep",
    "Rajasinga",
    "Karangasem",
    "Manggungan",
    "Cibereng",
    "Kendayakan"
  ],
  "Lelea": [
    "Tempel Kulon",
    "Tunggulpayung",
    "Tugu",
    "Nunuk",
    "Tempel",
    "Pangauban",
    "Telagasari",
    "Langgengsari",
    "Tamansari",
    "Lelea",
    "Cempeh"
  ],
  "Bangodua": [
    "Rancasari",
    "Mulyasari",
    "Bangodua",
    "Beduyut",
    "Karanggetas",
    "Tegalgirang",
    "Wanasari",
    "Malangsari"
  ],
  "Tukdana": [
    "Mekarsari",
    "Bodas",
    "Gadel",
    "Rancajawat",
    "Kerticala",
    "Sukamulya",
    "Karangkerta",
    "Cangko",
    "Pagedangan",
    "Sukaperna",
    "Sukadana",
    "Tukdana",
    "Lajer"
  ],
  "Widasari": [
    "Mekarsari",
    "Bangkaloa Ilir",
    "Widasari",
    "Kalensari",
    "Bunder",
    "Ujungaris",
    "Kongsijaya",
    "Ujungjaya",
    "Ujungpendokjaya",
    "Leuwigede",
    "Kasmaran"
  ],
  "Kertasemaya": [
    "Sukawera",
    "Tulungagung",
    "Jengkok",
    "Tegalwirangrong",
    "Manguntara",
    "Jambe",
    "Lemahayu",
    "Tenajar Kidul",
    "Kertasemaya",
    "Kliwed",
    "Tenajar",
    "Laranganjambe",
    "Tenajar Lor"
  ],
  "Sukagumiwang": [
    "Gedangan",
    "Cibeber",
    "Bondan",
    "Gunungsari",
    "Sukagumiwang",
    "Tersana",
    "Cadangpinggan"
  ],
  "Krangkeng": [
    "Tanjakan",
    "Purwajaya",
    "Kapringan",
    "Singakerta",
    "Dukuhjati",
    "Tegalmulya",
    "Kedungwungu",
    "Srengseng",
    "Luwunggesik",
    "Kalianyar",
    "Krangkeng"
  ],
  "Karangampel": [
    "Mundu",
    "Kaplonganlor",
    "Tanjungpura",
    "Tanjungsari",
    "Pringgacala",
    "Benda",
    "Sendang",
    "Karangampel Kidul",
    "Karangampel",
    "Dukuh Jeruk",
    "Dukuh Tengah"
  ],
  "Kedokan Bunder": [
    "Jayalaksana",
    "Kedokanbunder Wetan",
    "Kaplongan",
    "Kedokan Agung",
    "Kedokanbunder",
    "Jayawinangun",
    "Cangkingan"
  ],
  "Juntinyuat": [
    "Limbangan",
    "Segeran Kidul",
    "Segeran",
    "Juntiweden",
    "Juntikebon",
    "Dadap",
    "Juntinyuat",
    "Juntikedokan",
    "Pondoh",
    "Sambimaya",
    "Tinumpuk",
    "Lombang"
  ],
  "Sliyeg": [
    "Longok",
    "Sleman",
    "Tambi",
    "Sudikampiran",
    "Tambi Lor",
    "Sleman Lor",
    "Majasari",
    "Majasih",
    "Sliyeg",
    "Gadingan",
    "Mekargading",
    "Sliyeglor",
    "Tugu Kidul",
    "Tugu"
  ],
  "Jatibarang": [
    "Lobener Lor",
    "Sukalila",
    "Pilangsari",
    "Jatibarang Baru",
    "Bulak",
    "Bulak Lor",
    "Jatibarang",
    "Kebulen",
    "Pawidean",
    "Jatisawit",
    "Jatisawit Lor",
    "Krasak",
    "Kalimati",
    "Malangsemirang",
    "Lobener"
  ],
  "Balongan": [
    "Majakerta",
    "Tegalsembadra",
    "Sukareja",
    "Sukaurip",
    "Rawadalem",
    "Gelarmendala",
    "Tegalurung",
    "Balongan",
    "Sudimampir",
    "Sudimampirlor"
  ],
  "Indramayu": [
    "Tambak",
    "Telukagung",
    "Plumbon",
    "Dukuh",
    "Pekandangan Jaya",
    "Singaraja",
    "Singajaya",
    "Pekandangan",
    "Bojongsari",
    "Kepandean",
    "Karangmalang",
    "Karanganyar",
    "Lemahmekar",
    "Lemahabang",
    "Margadadi",
    "Paoman",
    "Karangsong",
    "Pabeanudik"
  ],
  "Sindang": [
    "Wanantara",
    "Panyindangan Kulon",
    "Rambatan Wetan",
    "Panyindangan Wetan",
    "Kenanga",
    "Terusan",
    "Dermayu",
    "Sindang",
    "Penganjang",
    "Babadan"
  ],
  "Cantigi": [
    "Cemara",
    "Cangkring",
    "Cantigi Kulon",
    "Cantigi Wetan",
    "Panyingkiran Lor",
    "Panyingkiran Kidul",
    "Lamarantarung"
  ],
  "Pasekan": [
    "Karanganyar",
    "Pagirikan",
    "Pasekan",
    "Brondong",
    "Pabeanilir",
    "Totoran"
  ],
  "Lohbener": [
    "Rambatan Kulon",
    "Kiajaran Kulon",
    "Kijaran Wetan",
    "Lanjan",
    "Langut",
    "Larangan",
    "Waru",
    "Legok",
    "Bojongslawi",
    "Lohbener",
    "Pamayahan",
    "Sindangkerta"
  ],
  "Arahan": [
    "Cidempet",
    "Sukasari",
    "Arahan Kidul",
    "Arahan Lor",
    "Linggajati",
    "Tawangsari",
    "Sukadadi",
    "Pranggong"
  ],
  "Losarang": [
    "Ranjeng",
    "Cemara Kulon",
    "Puntang",
    "Pegagan",
    "Rajaiyang",
    "Jangga",
    "Jumbleng",
    "Pangkalan",
    "Losarang",
    "Muntur",
    "Santing"
  ],
  "Kandanghaur": [
    "Soge",
    "Curug",
    "Pranti",
    "Wirakanan",
    "Karangmulya",
    "Karanganyar",
    "Wirapanjunan",
    "Parean Girang",
    "Bulak",
    "Ilir",
    "Eretan Wetan",
    "Eretan Kulon"
  ],
  "Bongas": [
    "Plawangan",
    "Cipedang",
    "Sidamulya",
    "Margamulya",
    "Kertajaya",
    "Bongas",
    "Cipaat",
    "Kertamulya"
  ],
  "Anjatan": [
    "Anjatan Utara",
    "Mangunjaya",
    "Bugistua",
    "Bugis",
    "Salamdarma",
    "Kedungwungu",
    "Wanguk",
    "Lempuyang",
    "Kopyah",
    "Anjatan Baru",
    "Anjatan",
    "Cilandak",
    "Cilandak Lor"
  ],
  "Sukra": [
    "Karanglayung",
    "Bogor",
    "Sukra",
    "Ujunggebang",
    "Tegaltaman",
    "Sukrawetan",
    "Sumuradem",
    "Sumuradem Timur"
  ],
  "Patrol": [
    "Limpas",
    "Patrol",
    "Arjasari",
    "Sukahaji",
    "Bugel",
    "Patrollor",
    "Patrol Baru",
    "Mekarsari"
  ]
} as const

export const indramayuDistricts = Object.keys(indramayuRegions)

export function villagesForDistrict(district: string) {
  return indramayuRegions[district as keyof typeof indramayuRegions] ?? []
}
