// Generated from docs/database/Master-Data.xlsx by scripts/generate-master-data-seed.mjs.
// Do not edit this file manually; update the workbook and rerun the generator.

export const masterDataSeed = {
  "departments": [
    {
      "id": "BPH",
      "code": "BPH",
      "name": "Badan Pengurus Harian"
    },
    {
      "id": "EKRAF",
      "code": "EKRAF",
      "name": "Ekonomi Kreatif"
    },
    {
      "id": "HPM",
      "code": "HPM",
      "name": "Hubungan & Pengabdian Masyarakat"
    },
    {
      "id": "KAD",
      "code": "KAD",
      "name": "Kaderisasi"
    },
    {
      "id": "KAJ",
      "code": "KAJ",
      "name": "Kajian & Advokasi"
    },
    {
      "id": "KOMDIGI",
      "code": "KOMDIGI",
      "name": "Komunikasi & Digitalisasi"
    },
    {
      "id": "PSDA",
      "code": "PSDA",
      "name": "Pengembangan Sumber Daya Anggota"
    }
  ],
  "positions": [
    {
      "id": "anggota_ekraf",
      "name": "Anggota Departemen Ekonomi Kreatif",
      "departmentId": "EKRAF"
    },
    {
      "id": "anggota_hpm",
      "name": "Anggota Departemen Hubungan & Pengabdian Masyarakat",
      "departmentId": "HPM"
    },
    {
      "id": "anggota_kad",
      "name": "Anggota Departemen Kaderisasi",
      "departmentId": "KAD"
    },
    {
      "id": "anggota_kaj",
      "name": "Anggota Departemen Kajian & Advokasi",
      "departmentId": "KAJ"
    },
    {
      "id": "anggota_komdigi",
      "name": "Anggota Departemen Komunikasi & Digitalisasi",
      "departmentId": "KOMDIGI"
    },
    {
      "id": "anggota_psda",
      "name": "Anggota Departemen Pengembangan Sumber Daya Anggota",
      "departmentId": "PSDA"
    },
    {
      "id": "bendum_1",
      "name": "Bendahara Umum I",
      "departmentId": "BPH"
    },
    {
      "id": "bendum_2",
      "name": "Bendahara Umum II",
      "departmentId": "BPH"
    },
    {
      "id": "kadep_ekraf",
      "name": "Ketua Departemen Ekonomi Kreatif",
      "departmentId": "EKRAF"
    },
    {
      "id": "kadep_hpm",
      "name": "Ketua Departemen Hubungan & Pengabdian Masyarakat",
      "departmentId": "HPM"
    },
    {
      "id": "kadep_kad",
      "name": "Ketua Departemen Kaderisasi",
      "departmentId": "KAD"
    },
    {
      "id": "kadep_kaj",
      "name": "Ketua Departemen Kajian & Advokasi",
      "departmentId": "KAJ"
    },
    {
      "id": "kadep_komdigi",
      "name": "Ketua Departemen Komunikasi & Digitalisasi",
      "departmentId": "KOMDIGI"
    },
    {
      "id": "kadep_psda",
      "name": "Ketua Departemen Pengembangan Sumber Daya Anggota",
      "departmentId": "PSDA"
    },
    {
      "id": "ketum",
      "name": "Ketua Umum",
      "departmentId": "BPH"
    },
    {
      "id": "sekdep_ekraf",
      "name": "Sekretaris Departemen Ekonomi Kreatif",
      "departmentId": "EKRAF"
    },
    {
      "id": "sekdep_hpm",
      "name": "Sekretaris Departemen Hubungan & Pengabdian Masyarakat",
      "departmentId": "HPM"
    },
    {
      "id": "sekdep_kad",
      "name": "Sekretaris Departemen Kaderisasi",
      "departmentId": "KAD"
    },
    {
      "id": "sekdep_kaj",
      "name": "Sekretaris Departemen Kajian & Advokasi",
      "departmentId": "KAJ"
    },
    {
      "id": "sekdep_komdigi",
      "name": "Sekretaris Departemen Komunikasi & Digitalisasi",
      "departmentId": "KOMDIGI"
    },
    {
      "id": "sekdep_psda",
      "name": "Sekretaris Departemen Pengembangan Sumber Daya Anggota",
      "departmentId": "PSDA"
    },
    {
      "id": "sekum_1",
      "name": "Sekretaris Umum I",
      "departmentId": "BPH"
    },
    {
      "id": "sekum_2",
      "name": "Sekretaris Umum II",
      "departmentId": "BPH"
    },
    {
      "id": "waketum",
      "name": "Wakil Ketua Umum",
      "departmentId": "BPH"
    }
  ],
  "programs": [
    {
      "id": "prog_bph_rapat_pleno_1",
      "name": "Rapat Pleno 1",
      "departmentId": "BPH",
      "scale": "Kecil",
      "description": "Membahas, memperbarui, dan mengesahkan pedoman kaderisasi, SOP, dan modul organisasi .",
      "status": "PLANNED"
    },
    {
      "id": "prog_bph_lpj_triwulan",
      "name": "LPJ Triwulan",
      "departmentId": "BPH",
      "scale": "Kecil",
      "description": "Evaluasi capaian dan kendala program kerja selama setengah periode .",
      "status": "PLANNED"
    },
    {
      "id": "prog_bph_pengarsipan_database",
      "name": "Pengarsipan Database",
      "departmentId": "BPH",
      "scale": "Kecil",
      "description": "Pendataan anggota, pengurus, demisioner, dan alumni via Google Formulir .",
      "status": "PLANNED"
    },
    {
      "id": "prog_bph_manajemen_surat",
      "name": "Manajemen Surat",
      "departmentId": "BPH",
      "scale": "Kecil",
      "description": "Pengelolaan surat masuk dan keluar agar tertata rapi dan terstruktur .",
      "status": "PLANNED"
    },
    {
      "id": "prog_bph_rapat_evaluasi_proker",
      "name": "Rapat Evaluasi Proker",
      "departmentId": "BPH",
      "scale": "Kecil",
      "description": "Evaluasi kekurangan dan kinerja panitia maksimal H+7 setelah kegiatan .",
      "status": "PLANNED"
    },
    {
      "id": "prog_bph_rapat_dwi_wulan",
      "name": "Rapat Dwi Wulan",
      "departmentId": "BPH",
      "scale": "Kecil",
      "description": "Rapat koordinasi rutin dua bulan sekali antara Kadep dan Sekdep .",
      "status": "PLANNED"
    },
    {
      "id": "prog_bph_sosialisasi_sop_ikmi",
      "name": "Sosialisasi SOP IKMI",
      "departmentId": "BPH",
      "scale": "Kecil",
      "description": "Pemahaman alur administrasi kepada seluruh pengurus .",
      "status": "PLANNED"
    },
    {
      "id": "prog_bph_struktur_organigram",
      "name": "Struktur Organigram",
      "departmentId": "BPH",
      "scale": "Kecil",
      "description": "Pembuatan dan penetapan desain struktur kepengurusan .",
      "status": "PLANNED"
    },
    {
      "id": "prog_bph_kalender_kegiatan",
      "name": "Kalender Kegiatan",
      "departmentId": "BPH",
      "scale": "Kecil",
      "description": "Penyusunan jadwal seluruh program kerja dan agenda organisasi .",
      "status": "PLANNED"
    },
    {
      "id": "prog_bph_pembukuan",
      "name": "Pembukuan",
      "departmentId": "BPH",
      "scale": "Kecil",
      "description": "Pencatatan transaksi keuangan di MS Word dan buku catatan .",
      "status": "PLANNED"
    },
    {
      "id": "prog_bph_iuran_uang_kegiatan",
      "name": "Iuran Uang Kegiatan",
      "departmentId": "BPH",
      "scale": "Kecil",
      "description": "Menagih iuran kegiatan kepada panitia dan pengurus .",
      "status": "PLANNED"
    },
    {
      "id": "prog_bph_laporan_keuangan",
      "name": "Laporan Keuangan",
      "departmentId": "BPH",
      "scale": "Kecil",
      "description": "Publikasi laporan transparansi keuangan kepada pengurus .",
      "status": "PLANNED"
    },
    {
      "id": "prog_kad_prabumi",
      "name": "PRABUMI",
      "departmentId": "KAD",
      "scale": "Besar",
      "description": "Penerimaan anggota baru sebagai wadah kaderisasi awal .",
      "status": "PLANNED"
    },
    {
      "id": "prog_kad_makrab",
      "name": "MAKRAB",
      "departmentId": "KAD",
      "scale": "Besar",
      "description": "Malam keakraban untuk mempererat hubungan antar anggota dan pengurus .",
      "status": "PLANNED"
    },
    {
      "id": "prog_kad_ekspedisi_kampus",
      "name": "Ekspedisi Kampus",
      "departmentId": "KAD",
      "scale": "Kecil",
      "description": "Sosialisasi dan pengenalan IKMI ke berbagai kampus di Cirebon .",
      "status": "PLANNED"
    },
    {
      "id": "prog_kad_sapa_rasa",
      "name": "Sapa Rasa",
      "departmentId": "KAD",
      "scale": "Kecil",
      "description": "Forum santai untuk menjaga keharmonisan internal organisasi .",
      "status": "PLANNED"
    },
    {
      "id": "prog_kaj_diskusi_panel",
      "name": "Diskusi Panel",
      "departmentId": "KAJ",
      "scale": "Kecil",
      "description": "Pembahasan isu daerah antara pemerintah dan masyarakat .",
      "status": "PLANNED"
    },
    {
      "id": "prog_kaj_warlit",
      "name": "WARLIT",
      "departmentId": "KAJ",
      "scale": "Kecil",
      "description": "Warung Literasi sebagai wadah diskusi kritis dan intelektual .",
      "status": "PLANNED"
    },
    {
      "id": "prog_kaj_refleksi_hari_besar",
      "name": "Refleksi Hari Besar",
      "departmentId": "KAJ",
      "scale": "Kecil",
      "description": "Diskusi pemahaman peristiwa nasional yang dijadikan hari besar .",
      "status": "PLANNED"
    },
    {
      "id": "prog_psda_baskara",
      "name": "BASKARA",
      "departmentId": "PSDA",
      "scale": "Kecil",
      "description": "Pelatihan intensif bahasa Jawa Kromo dan etika (unggah-ungguh) .",
      "status": "PLANNED"
    },
    {
      "id": "prog_psda_cimanuk",
      "name": "CIMANUK",
      "departmentId": "PSDA",
      "scale": "Kecil",
      "description": "Program akselerasi keahlian praktis dan pemetaan talenta anggota .",
      "status": "PLANNED"
    },
    {
      "id": "prog_psda_reang",
      "name": "REANG",
      "departmentId": "PSDA",
      "scale": "Kecil",
      "description": "Kegiatan rekreasi non-formal untuk menjaga kesehatan mental anggota .",
      "status": "PLANNED"
    },
    {
      "id": "prog_ekraf_kunjungan_industri",
      "name": "Kunjungan Industri",
      "departmentId": "EKRAF",
      "scale": "Kecil",
      "description": "Observasi langsung ke dunia kerja untuk memahami budaya profesional .",
      "status": "PLANNED"
    },
    {
      "id": "prog_ekraf_seragam_dan_lanyard",
      "name": "Seragam & Lanyard",
      "departmentId": "EKRAF",
      "scale": "Kecil",
      "description": "Pembuatan identitas formal pengurus untuk meningkatkan kredibilitas .",
      "status": "PLANNED"
    },
    {
      "id": "prog_ekraf_pembukuan_ekotif",
      "name": "Pembukuan Ekotif",
      "departmentId": "EKRAF",
      "scale": "Kecil",
      "description": "Laporan bulanan hasil usaha ekonomi kreatif organisasi .",
      "status": "PLANNED"
    },
    {
      "id": "prog_ekraf_jual_snack_dan_nasi_box",
      "name": "Jual Snack & Nasi Box",
      "departmentId": "EKRAF",
      "scale": "Kecil",
      "description": "Penjualan makanan untuk menambah pemasukan dana organisasi .",
      "status": "PLANNED"
    },
    {
      "id": "prog_ekraf_pendataan_usaha",
      "name": "Pendataan Usaha",
      "departmentId": "EKRAF",
      "scale": "Kecil",
      "description": "Mendata dan mempromosikan unit usaha milik anggota IKMI .",
      "status": "PLANNED"
    },
    {
      "id": "prog_komdigi_company_profile",
      "name": "Company Profile",
      "departmentId": "KOMDIGI",
      "scale": "Kecil",
      "description": "Pembuatan video branding profesional mengenai profil IKMI .",
      "status": "PLANNED"
    },
    {
      "id": "prog_komdigi_kelola_medsos",
      "name": "Kelola Medsos",
      "departmentId": "KOMDIGI",
      "scale": "Kecil",
      "description": "Publikasi kegiatan dan peningkatan eksistensi di media sosial .",
      "status": "PLANNED"
    },
    {
      "id": "prog_komdigi_pelatihan_internal",
      "name": "Pelatihan Internal",
      "departmentId": "KOMDIGI",
      "scale": "Kecil",
      "description": "Pengembangan keterampilan teknis bagi anggota divisi .",
      "status": "PLANNED"
    },
    {
      "id": "prog_komdigi_podcast_lentera_ayu",
      "name": "Podcast Lentera Ayu",
      "departmentId": "KOMDIGI",
      "scale": "Kecil",
      "description": "Media audio digital untuk eksplorasi berbagai topik informasi .",
      "status": "PLANNED"
    },
    {
      "id": "prog_komdigi_kabar_indramayu",
      "name": "Kabar Indramayu",
      "departmentId": "KOMDIGI",
      "scale": "Kecil",
      "description": "Publikasi konten edukatif mengenai potensi dan budaya daerah .",
      "status": "PLANNED"
    },
    {
      "id": "prog_hpm_ikmi_sosial",
      "name": "IKMI Sosial",
      "departmentId": "HPM",
      "scale": "Besar",
      "description": "Bakti sosial sukarela sebagai wujud pengabdian masyarakat .",
      "status": "PLANNED"
    },
    {
      "id": "prog_hpm_ultah_ikmi",
      "name": "Ultah IKMI",
      "departmentId": "HPM",
      "scale": "Besar",
      "description": "Perayaan hari lahir IKMI sebagai momen refleksi organisasi .",
      "status": "PLANNED"
    },
    {
      "id": "prog_hpm_ikmi_peduli",
      "name": "IKMI Peduli",
      "departmentId": "HPM",
      "scale": "Kecil",
      "description": "Aksi sosial untuk menumbuhkan rasa solidaritas terhadap sesama .",
      "status": "PLANNED"
    },
    {
      "id": "prog_hpm_ngobor",
      "name": "Ngobor",
      "departmentId": "HPM",
      "scale": "Kecil",
      "description": "Silaturahmi dan diskusi santai antar organisasi daerah (orda) .",
      "status": "PLANNED"
    },
    {
      "id": "prog_hpm_sospen",
      "name": "Sospen",
      "departmentId": "HPM",
      "scale": "Kecil",
      "description": "Sosialisasi pentingnya pendidikan tinggi kepada pelajar .",
      "status": "PLANNED"
    },
    {
      "id": "prog_bph_pelantikan",
      "name": "Pelantikan",
      "departmentId": "BPH",
      "scale": "Kalender",
      "description": "Agenda kalender IKMI: Pelantikan",
      "status": "PLANNED"
    },
    {
      "id": "prog_kaj_warlit_tambak",
      "name": "Warlit Tambak",
      "departmentId": "KAJ",
      "scale": "Kalender",
      "description": "Agenda kalender IKMI: Warlit Tambak",
      "status": "PLANNED"
    },
    {
      "id": "prog_kaj_kajian_konsol",
      "name": "Kajian Konsol",
      "departmentId": "KAJ",
      "scale": "Kalender",
      "description": "Agenda kalender IKMI: Kajian Konsol",
      "status": "PLANNED"
    },
    {
      "id": "prog_kaj_konsol_walkot",
      "name": "Konsol walkot",
      "departmentId": "KAJ",
      "scale": "Kalender",
      "description": "Agenda kalender IKMI: Konsol walkot",
      "status": "PLANNED"
    },
    {
      "id": "prog_komdigi_company_profil_ikmi",
      "name": "Company Profil IKMI",
      "departmentId": "KOMDIGI",
      "scale": "Kalender",
      "description": "Agenda kalender IKMI: Company Profil IKMI",
      "status": "PLANNED"
    },
    {
      "id": "prog_kaj_refleksi_buruh",
      "name": "Refleksi Buruh",
      "departmentId": "KAJ",
      "scale": "Kalender",
      "description": "Agenda kalender IKMI: Refleksi Buruh",
      "status": "PLANNED"
    },
    {
      "id": "prog_bph_raker",
      "name": "RAKER",
      "departmentId": "BPH",
      "scale": "Kalender",
      "description": "Agenda kalender IKMI: RAKER",
      "status": "PLANNED"
    },
    {
      "id": "prog_bph_sosialisasi_sop",
      "name": "Sosialisasi SOP",
      "departmentId": "BPH",
      "scale": "Kalender",
      "description": "Agenda kalender IKMI: Sosialisasi SOP",
      "status": "PLANNED"
    },
    {
      "id": "prog_bph_rapat_dwi",
      "name": "Rapat Dwi",
      "departmentId": "BPH",
      "scale": "Kalender",
      "description": "Agenda kalender IKMI: Rapat Dwi",
      "status": "PLANNED"
    },
    {
      "id": "prog_ekraf_pembuatan_pdh",
      "name": "Pembuatan PDH",
      "departmentId": "EKRAF",
      "scale": "Kalender",
      "description": "Agenda kalender IKMI: Pembuatan PDH",
      "status": "PLANNED"
    },
    {
      "id": "prog_bph_diagram_kepengurusan",
      "name": "Diagram Kepengurusan",
      "departmentId": "BPH",
      "scale": "Kalender",
      "description": "Agenda kalender IKMI: Diagram Kepengurusan",
      "status": "PLANNED"
    },
    {
      "id": "prog_komdigi_podcast_ayu",
      "name": "Podcast Ayu",
      "departmentId": "KOMDIGI",
      "scale": "Kalender",
      "description": "Agenda kalender IKMI: Podcast Ayu",
      "status": "PLANNED"
    },
    {
      "id": "prog_bph_rapat_evaluasi",
      "name": "Rapat Evaluasi",
      "departmentId": "BPH",
      "scale": "Kalender",
      "description": "Agenda kalender IKMI: Rapat Evaluasi",
      "status": "PLANNED"
    },
    {
      "id": "prog_bph_rapat_triwulan",
      "name": "Rapat triwulan",
      "departmentId": "BPH",
      "scale": "Kalender",
      "description": "Agenda kalender IKMI: Rapat triwulan",
      "status": "PLANNED"
    },
    {
      "id": "prog_hpm_ikmi_dugawe",
      "name": "IKMI Dugawe",
      "departmentId": "HPM",
      "scale": "Kalender",
      "description": "Agenda kalender IKMI: IKMI Dugawe",
      "status": "PLANNED"
    }
  ],
  "members": [
    {
      "id": "member_01_raden_hafidz_rahmatullah",
      "name": "Raden Hafidz Rahmatullah",
      "email": "radenhafidz2603@gmail.com",
      "sourceEmail": "radenhafidz2603@gmail.com",
      "positionName": "Ketua Umum",
      "birthInfo": "Indramayu, 26 Maret 2001",
      "phone": "81515901605",
      "address": "DS. Nanggung, Kec. Terisi Kab. Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210131/12_afbdbb.png",
      "photoPublicId": "12_afbdbb",
      "roleId": "super_admin",
      "departmentId": "BPH",
      "positionId": "ketum"
    },
    {
      "id": "member_02_muhamad_walid",
      "name": "Muhamad Walid",
      "email": "weloouyee@gmail.com",
      "sourceEmail": "Weloouyee@gmail.com",
      "positionName": "Wakil Ketua Umum",
      "birthInfo": "Indramayu 23 Agustus 2005",
      "phone": "895711498787",
      "address": "Ds. Linggajati, Kec. Arahan, Kab. Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781214225/Muhamad_Walid_h6ytvj.png",
      "photoPublicId": "Muhamad_Walid_h6ytvj",
      "roleId": "super_admin",
      "departmentId": "BPH",
      "positionId": "waketum"
    },
    {
      "id": "member_03_soliha",
      "name": "Soliha",
      "email": "soliha0803@gmail.com",
      "sourceEmail": "soliha0803@gmail.com",
      "positionName": "Sekretaris Umum I",
      "birthInfo": "Indramayu, 08 Maret 2005",
      "phone": "83841442158",
      "address": "Desa Wanguk Kec. Anjatan Kab. Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781214164/Soliha_jjexp6.png",
      "photoPublicId": "Soliha_jjexp6",
      "roleId": "admin_sekretaris",
      "departmentId": "BPH",
      "positionId": "sekum_1"
    },
    {
      "id": "member_04_atinah",
      "name": "Atinah",
      "email": "atinah140@gmail.com",
      "sourceEmail": "atinah140@gmail.com",
      "positionName": "Sekretaris Umum II",
      "birthInfo": "Indramayu, 14 Mei 2004",
      "phone": "83120974037",
      "address": "Ds. Sudimampir lor, Blok. Kayen Kec. Balongan, Kab. Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781214244/Atinah_vaaejf.png",
      "photoPublicId": "Atinah_vaaejf",
      "roleId": "user",
      "departmentId": "BPH",
      "positionId": "sekum_2"
    },
    {
      "id": "member_05_hallimatul_syahdiyah",
      "name": "Hallimatul Syahdiyah",
      "email": "hallimatulsyahdiyah@gmail.com",
      "sourceEmail": "hallimatulsyahdiyah@gmail.com",
      "positionName": "Bendahara Umum I",
      "birthInfo": "Indramayu, 07 Juli 2004",
      "phone": "89512512303",
      "address": "Ds. Sudimampir lor, Blok. Kayen Kec. Balongan, Kab. Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781214161/Hallimatul_Syahdiyah_ksuenz.png",
      "photoPublicId": "Hallimatul_Syahdiyah_ksuenz",
      "roleId": "admin_bendahara",
      "departmentId": "BPH",
      "positionId": "bendum_1"
    },
    {
      "id": "member_06_uswatun_hasanah",
      "name": "Uswatun Hasanah",
      "email": "atunnnmm@gmail.com",
      "sourceEmail": "Atunnnmm@gmail.com",
      "positionName": "Bendahara Umum II",
      "birthInfo": "Indramayu, 13 April 2006",
      "phone": "8119871836",
      "address": "Sabrang Wetan, Kec. Bongas, Kab. Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781214171/Uswatun_Hasanah_ymynar.png",
      "photoPublicId": "Uswatun_Hasanah_ymynar",
      "roleId": "user",
      "departmentId": "BPH",
      "positionId": "bendum_2"
    },
    {
      "id": "member_07_mochammad_naufal_hilmy",
      "name": "Mochammad Naufal Hilmy",
      "email": "hilmynaufal937@gmail.com",
      "sourceEmail": "hilmynaufal937@gmail.com",
      "positionName": "Ketua Departemen Kaderisasi",
      "birthInfo": "Indramayu, 02 April 2006",
      "phone": "83870722557",
      "address": "Sukagumiwang, Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210131/17_nhh5dq.png",
      "photoPublicId": "17_nhh5dq",
      "roleId": "user",
      "departmentId": "KAD",
      "positionId": "kadep_kad"
    },
    {
      "id": "member_08_derli_yanah",
      "name": "Derli Yanah",
      "email": "yanahderli@gmail.com",
      "sourceEmail": "Yanahderli@gmail.com",
      "positionName": "Sekretaris Departemen Kaderisasi",
      "birthInfo": "Indramayu, 22 Maret 2007",
      "phone": "82115395412",
      "address": "Ds. Rancasari, Kec. Bangodua, Kab. Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210132/18_adupkq.png",
      "photoPublicId": "18_adupkq",
      "roleId": "user",
      "departmentId": "KAD",
      "positionId": "sekdep_kad"
    },
    {
      "id": "member_09_sulthon_azizan_zanuar",
      "name": "Sulthon Azizan Zanuar",
      "email": "sulthonazizanzanuar@gmail.com",
      "sourceEmail": "sulthonazizanzanuar@gmail.com",
      "positionName": "Anggota Departemen Kaderisasi",
      "birthInfo": "Cirebon, 22 Desember 2003",
      "phone": "83195992117",
      "address": "Ds. Mulyasari, Kec. Bangodua, Kab. Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210131/19_pxbipj.png",
      "photoPublicId": "19_pxbipj",
      "roleId": "user",
      "departmentId": "KAD",
      "positionId": "anggota_kad"
    },
    {
      "id": "member_10_fikri_haikal_fasa",
      "name": "Fikri Haikal Fasa",
      "email": "member-10@ikmi.local",
      "sourceEmail": "-",
      "positionName": "Anggota Departemen Kaderisasi",
      "birthInfo": "Indramayu, 15 Mei 2004",
      "phone": "85872890581",
      "address": "Sukra, Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210131/20_eonx1o.png",
      "photoPublicId": "20_eonx1o",
      "roleId": "user",
      "departmentId": "KAD",
      "positionId": "anggota_kad"
    },
    {
      "id": "member_11_ahmad_syahid",
      "name": "Ahmad Syahid",
      "email": "nagipleto@gmail.com",
      "sourceEmail": "Nagipleto@gmail.com",
      "positionName": "Ketua Departemen Pengembangan Sumber Daya Anggota",
      "birthInfo": "Indramayu, 18 Maret 2005",
      "phone": "87729210199",
      "address": "Dusun Sepat RT/RW 10/04 Ds. Kedungwungu, Kec. Anjatan Kab Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210139/28_tvaz5k.png",
      "photoPublicId": "28_tvaz5k",
      "roleId": "user",
      "departmentId": "PSDA",
      "positionId": "kadep_psda"
    },
    {
      "id": "member_12_haidar_rasyikh_mubarok",
      "name": "Haidar Rasyikh Mubarok",
      "email": "kakaacik65@gmail.com",
      "sourceEmail": "kakaacik65@gmail.com",
      "positionName": "Sekretaris Departemen Pengembangan Sumber Daya Anggota",
      "birthInfo": "Indramayu, 28 Mei 2006",
      "phone": "85150005656",
      "address": "Ds. Lempuyang, Kec. Anjatan, Kab. Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210138/29_zqjltt.png",
      "photoPublicId": "29_zqjltt",
      "roleId": "user",
      "departmentId": "PSDA",
      "positionId": "sekdep_psda"
    },
    {
      "id": "member_13_akhmad_yani",
      "name": "Akhmad Yani",
      "email": "akhmadyani209@gmail.com",
      "sourceEmail": "akhmadyani209@gmail.com",
      "positionName": "Anggota Departemen Pengembangan Sumber Daya Anggota",
      "birthInfo": "Indramayu, 19 November 2007",
      "phone": "89661245331",
      "address": "Desa Patrol Lor Kecamatan Patrol, Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210137/32_pccq3z.png",
      "photoPublicId": "32_pccq3z",
      "roleId": "user",
      "departmentId": "PSDA",
      "positionId": "anggota_psda"
    },
    {
      "id": "member_14_elok_satria_mulyawati",
      "name": "Elok Satria Mulyawati",
      "email": "satrianimulyawatie@gmail.com",
      "sourceEmail": "Satrianimulyawatie@gmail.com",
      "positionName": "Anggota Departemen Pengembangan Sumber Daya Anggota",
      "birthInfo": "Sumedang, 21 November 2006",
      "phone": "83873100407",
      "address": "Blok Jengkok Barat, RT.007/RW.002, Kec. Kertasemaya, Kab. Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210138/30_gpctwl.png",
      "photoPublicId": "30_gpctwl",
      "roleId": "user",
      "departmentId": "PSDA",
      "positionId": "anggota_psda"
    },
    {
      "id": "member_15_rifqi_ramadhani",
      "name": "Rifqi Ramadhani",
      "email": "rifqir630@gmail.com",
      "sourceEmail": "rifqir630@gmail.com",
      "positionName": "Anggota Departemen Pengembangan Sumber Daya Anggota",
      "birthInfo": "Indramayu, 03 oktober2007",
      "phone": "83191561723",
      "address": "Desa Cantigi Wetan, Kec. Cantigi Kab Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210137/31_cqsm9r.png",
      "photoPublicId": "31_cqsm9r",
      "roleId": "user",
      "departmentId": "PSDA",
      "positionId": "anggota_psda"
    },
    {
      "id": "member_16_muchammad_fachri",
      "name": "Muchammad Fachri",
      "email": "muchammadfachri229@gmail.com",
      "sourceEmail": "muchammadfachri229@gmail.com",
      "positionName": "Anggota Departemen Pengembangan Sumber Daya Anggota",
      "birthInfo": "Indramayu, 29 Mei 2007",
      "phone": "81313880879",
      "address": "Tulungagung, Kertasemaya, Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210137/33_nsmxqq.png",
      "photoPublicId": "33_nsmxqq",
      "roleId": "user",
      "departmentId": "PSDA",
      "positionId": "anggota_psda"
    },
    {
      "id": "member_17_azzumardi_azra",
      "name": "Azzumardi Azra",
      "email": "azzumardi13.01@gmail.com",
      "sourceEmail": "azzumardi13.01@gmail.com",
      "positionName": "Ketua Departemen Kajian & Advokasi",
      "birthInfo": "Indramayu, 13 Januari 2006",
      "phone": "881025288593",
      "address": "Sukalila, Jatibarang, Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210135/22_f2iuaa.png",
      "photoPublicId": "22_f2iuaa",
      "roleId": "user",
      "departmentId": "KAJ",
      "positionId": "kadep_kaj"
    },
    {
      "id": "member_18_amara_dilla_dia_dina",
      "name": "Amara Dilla Dia Dina",
      "email": "amaradilla03@gmail.com",
      "sourceEmail": "amaradilla03@gmail.com",
      "positionName": "Sekretaris Departemen Kajian & Advokasi",
      "birthInfo": "Indramayu, 03 April 2005",
      "phone": "85864479139",
      "address": "Ds. Segeran kidul, Kec. Juntinyuat, Kab. Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210137/23_dwhbb5.png",
      "photoPublicId": "23_dwhbb5",
      "roleId": "user",
      "departmentId": "KAJ",
      "positionId": "sekdep_kaj"
    },
    {
      "id": "member_19_muhammad_abdul_aziz",
      "name": "Muhammad Abdul Aziz",
      "email": "abdulazizindramayu12@gmail.com",
      "sourceEmail": "Abdulazizindramayu12@gmail.com",
      "positionName": "Anggota Departemen Kajian & Advokasi",
      "birthInfo": "Indramayu, 08 November 2004",
      "phone": "85862991253",
      "address": "Ds. Krasak, Kec. Jatibarang, Kab. Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210134/26_qakokx.png",
      "photoPublicId": "26_qakokx",
      "roleId": "user",
      "departmentId": "KAJ",
      "positionId": "anggota_kaj"
    },
    {
      "id": "member_20_galih_satria_bontot",
      "name": "Galih Satria Bontot",
      "email": "galihsatriabontot12@gmail.com",
      "sourceEmail": "galihsatriabontot12@gmail.com",
      "positionName": "Anggota Departemen Kajian & Advokasi",
      "birthInfo": "Indramayu, 12 Maret 2007",
      "phone": "81572599019",
      "address": "Ds. Cipaat, Kec. Bongas, Kab. Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210135/25_xrc6xf.png",
      "photoPublicId": "25_xrc6xf",
      "roleId": "user",
      "departmentId": "KAJ",
      "positionId": "anggota_kaj"
    },
    {
      "id": "member_21_sholelil_ulka_ababiluna",
      "name": "Sholelil Ulka Ababiluna",
      "email": "sholelilulka0@gmail.com",
      "sourceEmail": "sholelilulka0@gmail.com",
      "positionName": "Anggota Departemen Kajian & Advokasi",
      "birthInfo": "Indramayu, 19 April 2004",
      "phone": "8979400501",
      "address": "Ds. Parean Girang, Kec. Kandanghaur Kab. Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210136/24_olucqn.png",
      "photoPublicId": "24_olucqn",
      "roleId": "user",
      "departmentId": "KAJ",
      "positionId": "anggota_kaj"
    },
    {
      "id": "member_22_faiz_ubaidilah_fazri",
      "name": "Faiz Ubaidilah Fazri",
      "email": "faizubaidilah2701@gmail.com",
      "sourceEmail": "Faizubaidilah2701@gmail.com",
      "positionName": "Ketua Departemen Hubungan & Pengabdian Masyarakat",
      "birthInfo": "Indramayu, 03 September 2005",
      "phone": "38147863967",
      "address": "Ds. Sumbon, Kec. Kroya, Kab. Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210146/47_tgsj44.png",
      "photoPublicId": "47_tgsj44",
      "roleId": "user",
      "departmentId": "HPM",
      "positionId": "kadep_hpm"
    },
    {
      "id": "member_23_abdul_hasib",
      "name": "Abdul Hasib",
      "email": "lelea200510@gmail.com",
      "sourceEmail": "lelea200510@gmail.com",
      "positionName": "Sekretaris Departemen Hubungan & Pengabdian Masyarakat",
      "birthInfo": "Indramayu, 25 Oktober 2005",
      "phone": "82128717408",
      "address": "Ds. Tempel Kec. Lelea Kab. Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210147/48_vqlamg.png",
      "photoPublicId": "48_vqlamg",
      "roleId": "user",
      "departmentId": "HPM",
      "positionId": "sekdep_hpm"
    },
    {
      "id": "member_24_very_kurniawan",
      "name": "Very Kurniawan",
      "email": "kvery9722@gmail.com",
      "sourceEmail": "Kvery9722@gmail.com",
      "positionName": "Anggota Departemen Hubungan & Pengabdian Masyarakat",
      "birthInfo": "Indramayu, 25 Maret 2007",
      "phone": "85169711121",
      "address": "Ds. Juntikebon, Blok. Tegal Gelap, RT/RW 004/004 Kec. Juntinyuat, Kab. Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210145/50_owsza0.png",
      "photoPublicId": "50_owsza0",
      "roleId": "user",
      "departmentId": "HPM",
      "positionId": "anggota_hpm"
    },
    {
      "id": "member_25_marcel_nur_mu_ijj",
      "name": "Marcel Nur Mu'ijj",
      "email": "acengtukce@gmail.com",
      "sourceEmail": "acengtukce@gmail.com",
      "positionName": "Anggota Departemen Hubungan & Pengabdian Masyarakat",
      "birthInfo": "Indramayu, 09 Maret 2007",
      "phone": "83168620827",
      "address": "Cikedung, Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210145/49_causkd.png",
      "photoPublicId": "49_causkd",
      "roleId": "user",
      "departmentId": "HPM",
      "positionId": "anggota_hpm"
    },
    {
      "id": "member_26_danu_pratama",
      "name": "Danu Pratama",
      "email": "danupratama627@gmail.com",
      "sourceEmail": "danupratama627@gmail.com",
      "positionName": "Anggota Departemen Hubungan & Pengabdian Masyarakat",
      "birthInfo": "Indramayu, 29 Juni 2007",
      "phone": "83839178019",
      "address": "Jl. Laut Patrol Lor Blok Mushola Al-Ishlah, Kec. Patrol Kab. Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210145/51_burwqi.png",
      "photoPublicId": "51_burwqi",
      "roleId": "user",
      "departmentId": "HPM",
      "positionId": "anggota_hpm"
    },
    {
      "id": "member_27_muhammad_muzaki",
      "name": "Muhammad Muzaki",
      "email": "zmuzaqi010@gmail.com",
      "sourceEmail": "zmuzaqi010@gmail.com",
      "positionName": "Ketua Departemen Ekonomi Kreatif",
      "birthInfo": "Indramayu, 17 Maret 2005",
      "phone": "82130256631",
      "address": "Kec. Patrol, Kab. Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210140/35_uijck4.png",
      "photoPublicId": "35_uijck4",
      "roleId": "user",
      "departmentId": "EKRAF",
      "positionId": "kadep_ekraf"
    },
    {
      "id": "member_28_reisya_kamalia_ihsana",
      "name": "Reisya Kamalia Ihsana",
      "email": "reisyaihsana@gmail.com",
      "sourceEmail": "reisyaihsana@gmail.com",
      "positionName": "Sekretaris Departemen Ekonomi Kreatif",
      "birthInfo": "Indramayu, 16 November 2006",
      "phone": "85187298490",
      "address": "Jl. Pabean Udik RT/RW 03/10, Kec. Indramayu, Kab. Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210140/36_weuvff.png",
      "photoPublicId": "36_weuvff",
      "roleId": "user",
      "departmentId": "EKRAF",
      "positionId": "sekdep_ekraf"
    },
    {
      "id": "member_29_farrah_rizka_rena_fadillah",
      "name": "Farrah Rizka Rena Fadillah",
      "email": "frrhfdhla@gmail.com",
      "sourceEmail": "Frrhfdhla@gmail.com",
      "positionName": "Anggota Departemen Ekonomi Kreatif",
      "birthInfo": "Indramayu, 27 Februari 2006",
      "phone": "813181503440",
      "address": "Ds. Eretan Wetan, Kec. Kandanghaur, Kab. Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210140/37_kormcc.png",
      "photoPublicId": "37_kormcc",
      "roleId": "user",
      "departmentId": "EKRAF",
      "positionId": "anggota_ekraf"
    },
    {
      "id": "member_30_saipul_ernawan",
      "name": "Saipul Ernawan",
      "email": "ipungernawan9@gmail.com",
      "sourceEmail": "ipungernawan9@gmail.com",
      "positionName": "Anggota Departemen Ekonomi Kreatif",
      "birthInfo": "Indramayu, 02 September 2004",
      "phone": "-",
      "address": "Ds. Cangkring, Blok. Pancer Pindang, Cantigi, Kab. Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210139/38_npspil.png",
      "photoPublicId": "38_npspil",
      "roleId": "user",
      "departmentId": "EKRAF",
      "positionId": "anggota_ekraf"
    },
    {
      "id": "member_31_riza_alraihany",
      "name": "Riza Alraihany",
      "email": "azieralraihany@gmail.com",
      "sourceEmail": "azieralraihany@gmail.com",
      "positionName": "Ketua Departemen Komunikasi & Digitalisasi",
      "birthInfo": "Indramayu, 30 November 2004",
      "phone": "83837106539",
      "address": "Ds. Cangkringan, Kec. Cantigi, Kab. Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210142/40_jj1x3k.png",
      "photoPublicId": "40_jj1x3k",
      "roleId": "admin_komdigi",
      "departmentId": "KOMDIGI",
      "positionId": "kadep_komdigi"
    },
    {
      "id": "member_32_siti_fatimah",
      "name": "Siti Fatimah",
      "email": "fatimmangel@gmail.com",
      "sourceEmail": "Fatimmangel@gmail.com",
      "positionName": "Sekretaris Departemen Komunikasi & Digitalisasi",
      "birthInfo": "Indramayu, 16 Mei 2006",
      "phone": "83842620963",
      "address": "Ds. Mekarjaya, Kec. Gantar, Kab. Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210143/41_bvox2c.png",
      "photoPublicId": "41_bvox2c",
      "roleId": "admin_komdigi",
      "departmentId": "KOMDIGI",
      "positionId": "sekdep_komdigi"
    },
    {
      "id": "member_33_naofal_william_atalah",
      "name": "Naofal William Atalah",
      "email": "naofalwilli@gmail.com",
      "sourceEmail": "naofalwilli@gmail.com",
      "positionName": "Anggota Departemen Komunikasi & Digitalisasi",
      "birthInfo": "Indramayu, 19 Maret 2005",
      "phone": "81311740001",
      "address": "Sukra, Kab. Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210143/43_eiqptp.png",
      "photoPublicId": "43_eiqptp",
      "roleId": "admin_komdigi",
      "departmentId": "KOMDIGI",
      "positionId": "anggota_komdigi"
    },
    {
      "id": "member_34_safitriani_syaroni",
      "name": "Safitriani Syaroni",
      "email": "safitrianisyahroni964@gmailcom",
      "sourceEmail": "Safitrianisyahroni964@gmailcom",
      "positionName": "Anggota Departemen Komunikasi & Digitalisasi",
      "birthInfo": "Indramayu, 19 Maret 2005",
      "phone": "8131542651",
      "address": "Ds. Curug, Blok. Cidongkol, Kec. Kandanghaur, Kab. Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210141/45_itkqc8.png",
      "photoPublicId": "45_itkqc8",
      "roleId": "admin_komdigi",
      "departmentId": "KOMDIGI",
      "positionId": "anggota_komdigi"
    },
    {
      "id": "member_35_siti_rohmawati",
      "name": "Siti Rohmawati",
      "email": "srohmawati697@gmail.com",
      "sourceEmail": "srohmawati697@gmail.com",
      "positionName": "Anggota Departemen Komunikasi & Digitalisasi",
      "birthInfo": "Indramayu, 25 Mei 2007",
      "phone": "81318147541",
      "address": "Blok. Tarilah Des. Kongsijaya Kec. Widasari Kab. Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210144/42_ki8rax.png",
      "photoPublicId": "42_ki8rax",
      "roleId": "admin_komdigi",
      "departmentId": "KOMDIGI",
      "positionId": "anggota_komdigi"
    },
    {
      "id": "member_36_ziantoro_nuji_wijaya",
      "name": "Ziantoro Nuji Wijaya",
      "email": "swiperjanganmencuri1204@gmail.com",
      "sourceEmail": "Swiperjanganmencuri1204@gmail.com",
      "positionName": "Anggota Departemen Komunikasi & Digitalisasi",
      "birthInfo": "Indramayu, 30 Februari 2005",
      "phone": "85280014245",
      "address": "Kec. Haurgeulis, Kab. Indramayu",
      "photoUrl": "https://res.cloudinary.com/dsgldeuuy/image/upload/v1781210142/44_cvldnc.png",
      "photoPublicId": "44_cvldnc",
      "roleId": "admin_komdigi",
      "departmentId": "KOMDIGI",
      "positionId": "anggota_komdigi"
    }
  ],
  "events": [
    {
      "id": "event_001_pelantikan",
      "programId": "prog_bph_pelantikan",
      "title": "Pelantikan",
      "description": "Agenda Pelantikan dari BPH.",
      "location": "IKMI Cirebon",
      "startDate": "2026-04-12T00:00:00.000Z",
      "endDate": "2026-04-12T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_002_warlit_tambak",
      "programId": "prog_kaj_warlit_tambak",
      "title": "Warlit Tambak",
      "description": "Agenda Warlit Tambak dari KAJ.",
      "location": "IKMI Cirebon",
      "startDate": "2026-04-16T00:00:00.000Z",
      "endDate": "2026-04-16T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_003_kajian_konsol",
      "programId": "prog_kaj_kajian_konsol",
      "title": "Kajian Konsol",
      "description": "Agenda Kajian Konsol dari KAJ.",
      "location": "IKMI Cirebon",
      "startDate": "2026-04-25T00:00:00.000Z",
      "endDate": "2026-04-25T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_004_konsol_walkot",
      "programId": "prog_kaj_konsol_walkot",
      "title": "Konsol walkot",
      "description": "Agenda Konsol walkot dari KAJ.",
      "location": "IKMI Cirebon",
      "startDate": "2026-04-28T00:00:00.000Z",
      "endDate": "2026-04-28T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_005_company_profil_ikmi",
      "programId": "prog_komdigi_company_profil_ikmi",
      "title": "Company Profil IKMI",
      "description": "Agenda Company Profil IKMI dari KOMDIGI.",
      "location": "IKMI Cirebon",
      "startDate": "2026-05-01T00:00:00.000Z",
      "endDate": "2026-05-01T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_006_refleksi_buruh",
      "programId": "prog_kaj_refleksi_buruh",
      "title": "Refleksi Buruh",
      "description": "Agenda Refleksi Buruh dari KAJ.",
      "location": "IKMI Cirebon",
      "startDate": "2026-05-04T00:00:00.000Z",
      "endDate": "2026-05-04T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_007_raker",
      "programId": "prog_bph_raker",
      "title": "RAKER",
      "description": "Agenda RAKER dari BPH.",
      "location": "IKMI Cirebon",
      "startDate": "2026-05-08T00:00:00.000Z",
      "endDate": "2026-05-08T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_008_warlit",
      "programId": "prog_kaj_warlit",
      "title": "Warlit",
      "description": "Agenda Warlit dari KAJ.",
      "location": "IKMI Cirebon",
      "startDate": "2026-05-14T00:00:00.000Z",
      "endDate": "2026-05-14T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_009_kalender_kegiatan",
      "programId": "prog_bph_kalender_kegiatan",
      "title": "Kalender Kegiatan",
      "description": "Agenda Kalender Kegiatan dari BPH.",
      "location": "IKMI Cirebon",
      "startDate": "2026-05-16T00:00:00.000Z",
      "endDate": "2026-05-16T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_010_sosialisasi_sop",
      "programId": "prog_bph_sosialisasi_sop",
      "title": "Sosialisasi SOP",
      "description": "Agenda Sosialisasi SOP dari BPH.",
      "location": "IKMI Cirebon",
      "startDate": "2026-05-17T00:00:00.000Z",
      "endDate": "2026-05-17T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_011_rapat_dwi",
      "programId": "prog_bph_rapat_dwi",
      "title": "Rapat Dwi",
      "description": "Agenda Rapat Dwi dari BPH.",
      "location": "IKMI Cirebon",
      "startDate": "2026-05-18T00:00:00.000Z",
      "endDate": "2026-05-18T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_012_pembuatan_pdh",
      "programId": "prog_ekraf_pembuatan_pdh",
      "title": "Pembuatan PDH",
      "description": "Agenda Pembuatan PDH dari EKRAF.",
      "location": "IKMI Cirebon",
      "startDate": "2026-05-20T00:00:00.000Z",
      "endDate": "2026-05-20T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_013_sapa_rasa",
      "programId": "prog_kad_sapa_rasa",
      "title": "Sapa Rasa",
      "description": "Agenda Sapa Rasa dari KAD.",
      "location": "IKMI Cirebon",
      "startDate": "2026-05-22T00:00:00.000Z",
      "endDate": "2026-05-22T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_014_baskara",
      "programId": "prog_psda_baskara",
      "title": "BASKARA",
      "description": "Agenda BASKARA dari PSDA.",
      "location": "IKMI Cirebon",
      "startDate": "2026-05-23T00:00:00.000Z",
      "endDate": "2026-05-23T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_015_warlit",
      "programId": "prog_kaj_warlit",
      "title": "Warlit",
      "description": "Agenda Warlit dari KAJ.",
      "location": "IKMI Cirebon",
      "startDate": "2026-05-28T00:00:00.000Z",
      "endDate": "2026-05-28T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_016_ekspedisi_kampus",
      "programId": "prog_kad_ekspedisi_kampus",
      "title": "Ekspedisi Kampus",
      "description": "Agenda Ekspedisi Kampus dari KAD.",
      "location": "IKMI Cirebon",
      "startDate": "2026-05-29T00:00:00.000Z",
      "endDate": "2026-05-29T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_017_reang",
      "programId": "prog_psda_reang",
      "title": "REANG",
      "description": "Agenda REANG dari PSDA.",
      "location": "IKMI Cirebon",
      "startDate": "2026-05-30T00:00:00.000Z",
      "endDate": "2026-05-30T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_018_diagram_kepengurusan",
      "programId": "prog_bph_diagram_kepengurusan",
      "title": "Diagram Kepengurusan",
      "description": "Agenda Diagram Kepengurusan dari BPH.",
      "location": "IKMI Cirebon",
      "startDate": "2026-06-01T00:00:00.000Z",
      "endDate": "2026-06-01T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_019_baskara",
      "programId": "prog_psda_baskara",
      "title": "BASKARA",
      "description": "Agenda BASKARA dari PSDA.",
      "location": "IKMI Cirebon",
      "startDate": "2026-06-05T00:00:00.000Z",
      "endDate": "2026-06-05T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_020_reang",
      "programId": "prog_psda_reang",
      "title": "REANG",
      "description": "Agenda REANG dari PSDA.",
      "location": "IKMI Cirebon",
      "startDate": "2026-06-12T00:00:00.000Z",
      "endDate": "2026-06-12T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_021_sapa_rasa",
      "programId": "prog_kad_sapa_rasa",
      "title": "Sapa Rasa",
      "description": "Agenda Sapa Rasa dari KAD.",
      "location": "IKMI Cirebon",
      "startDate": "2026-06-13T00:00:00.000Z",
      "endDate": "2026-06-13T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_022_podcast_ayu",
      "programId": "prog_komdigi_podcast_ayu",
      "title": "Podcast Ayu",
      "description": "Agenda Podcast Ayu dari KOMDIGI.",
      "location": "IKMI Cirebon",
      "startDate": "2026-06-14T00:00:00.000Z",
      "endDate": "2026-06-14T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_023_baskara",
      "programId": "prog_psda_baskara",
      "title": "BASKARA",
      "description": "Agenda BASKARA dari PSDA.",
      "location": "IKMI Cirebon",
      "startDate": "2026-06-20T00:00:00.000Z",
      "endDate": "2026-06-20T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_024_cimanuk",
      "programId": "prog_psda_cimanuk",
      "title": "CIMANUK",
      "description": "Agenda CIMANUK dari PSDA.",
      "location": "IKMI Cirebon",
      "startDate": "2026-06-22T00:00:00.000Z",
      "endDate": "2026-06-22T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_025_ikmi_sosial",
      "programId": "prog_hpm_ikmi_sosial",
      "title": "IKMI SOSIAL",
      "description": "Agenda IKMI SOSIAL dari HPM.",
      "location": "IKMI Cirebon",
      "startDate": "2026-06-28T00:00:00.000Z",
      "endDate": "2026-06-28T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_026_ikmi_sosial",
      "programId": "prog_hpm_ikmi_sosial",
      "title": "IKMI SOSIAL",
      "description": "Agenda IKMI SOSIAL dari HPM.",
      "location": "IKMI Cirebon",
      "startDate": "2026-06-29T00:00:00.000Z",
      "endDate": "2026-06-29T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_027_ikmi_sosial",
      "programId": "prog_hpm_ikmi_sosial",
      "title": "IKMI SOSIAL",
      "description": "Agenda IKMI SOSIAL dari HPM.",
      "location": "IKMI Cirebon",
      "startDate": "2026-06-30T00:00:00.000Z",
      "endDate": "2026-06-30T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_028_kunjungan_industri",
      "programId": "prog_ekraf_kunjungan_industri",
      "title": "Kunjungan Industri",
      "description": "Agenda Kunjungan Industri dari EKRAF.",
      "location": "IKMI Cirebon",
      "startDate": "2026-07-01T00:00:00.000Z",
      "endDate": "2026-07-01T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_029_ikmi_sosial",
      "programId": "prog_hpm_ikmi_sosial",
      "title": "IKMI SOSIAL",
      "description": "Agenda IKMI SOSIAL dari HPM.",
      "location": "IKMI Cirebon",
      "startDate": "2026-07-02T00:00:00.000Z",
      "endDate": "2026-07-02T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_030_baskara",
      "programId": "prog_psda_baskara",
      "title": "BASKARA",
      "description": "Agenda BASKARA dari PSDA.",
      "location": "IKMI Cirebon",
      "startDate": "2026-07-03T00:00:00.000Z",
      "endDate": "2026-07-03T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_031_sapa_rasa",
      "programId": "prog_kad_sapa_rasa",
      "title": "Sapa Rasa",
      "description": "Agenda Sapa Rasa dari KAD.",
      "location": "IKMI Cirebon",
      "startDate": "2026-07-04T00:00:00.000Z",
      "endDate": "2026-07-04T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_032_ikmi_peduli",
      "programId": "prog_hpm_ikmi_peduli",
      "title": "IKMI PEDULI",
      "description": "Agenda IKMI PEDULI dari HPM.",
      "location": "IKMI Cirebon",
      "startDate": "2026-07-05T00:00:00.000Z",
      "endDate": "2026-07-05T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_033_ikmi_sosial",
      "programId": "prog_hpm_ikmi_sosial",
      "title": "IKMI SOSIAL",
      "description": "Agenda IKMI SOSIAL dari HPM.",
      "location": "IKMI Cirebon",
      "startDate": "2026-07-06T00:00:00.000Z",
      "endDate": "2026-07-06T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_034_ikmi_sosial",
      "programId": "prog_hpm_ikmi_sosial",
      "title": "IKMI SOSIAL",
      "description": "Agenda IKMI SOSIAL dari HPM.",
      "location": "IKMI Cirebon",
      "startDate": "2026-07-07T00:00:00.000Z",
      "endDate": "2026-07-07T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_035_ikmi_sosial",
      "programId": "prog_hpm_ikmi_sosial",
      "title": "IKMI SOSIAL",
      "description": "Agenda IKMI SOSIAL dari HPM.",
      "location": "IKMI Cirebon",
      "startDate": "2026-07-08T00:00:00.000Z",
      "endDate": "2026-07-08T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_036_rapat_dwi",
      "programId": "prog_bph_rapat_dwi",
      "title": "Rapat Dwi",
      "description": "Agenda Rapat Dwi dari BPH.",
      "location": "IKMI Cirebon",
      "startDate": "2026-07-10T00:00:00.000Z",
      "endDate": "2026-07-10T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_037_rapat_evaluasi",
      "programId": "prog_bph_rapat_evaluasi",
      "title": "Rapat Evaluasi",
      "description": "Agenda Rapat Evaluasi dari BPH.",
      "location": "IKMI Cirebon",
      "startDate": "2026-07-11T00:00:00.000Z",
      "endDate": "2026-07-11T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_038_ekspedisi_kampus",
      "programId": "prog_kad_ekspedisi_kampus",
      "title": "Ekspedisi Kampus",
      "description": "Agenda Ekspedisi Kampus dari KAD.",
      "location": "IKMI Cirebon",
      "startDate": "2026-08-20T00:00:00.000Z",
      "endDate": "2026-08-20T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_039_sapa_rasa",
      "programId": "prog_kad_sapa_rasa",
      "title": "Sapa Rasa",
      "description": "Agenda Sapa Rasa dari KAD.",
      "location": "IKMI Cirebon",
      "startDate": "2026-08-22T00:00:00.000Z",
      "endDate": "2026-08-22T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_040_reang",
      "programId": "prog_psda_reang",
      "title": "REANG",
      "description": "Agenda REANG dari PSDA.",
      "location": "IKMI Cirebon",
      "startDate": "2026-08-28T00:00:00.000Z",
      "endDate": "2026-08-28T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_041_baskara",
      "programId": "prog_psda_baskara",
      "title": "BASKARA",
      "description": "Agenda BASKARA dari PSDA.",
      "location": "IKMI Cirebon",
      "startDate": "2026-08-29T00:00:00.000Z",
      "endDate": "2026-08-29T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_042_baskara",
      "programId": "prog_psda_baskara",
      "title": "BASKARA",
      "description": "Agenda BASKARA dari PSDA.",
      "location": "IKMI Cirebon",
      "startDate": "2026-09-04T00:00:00.000Z",
      "endDate": "2026-09-04T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_043_rapat_triwulan",
      "programId": "prog_bph_rapat_triwulan",
      "title": "Rapat triwulan",
      "description": "Agenda Rapat triwulan dari BPH.",
      "location": "IKMI Cirebon",
      "startDate": "2026-09-05T00:00:00.000Z",
      "endDate": "2026-09-05T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_044_ekspedisi_kampus",
      "programId": "prog_kad_ekspedisi_kampus",
      "title": "Ekspedisi Kampus",
      "description": "Agenda Ekspedisi Kampus dari KAD.",
      "location": "IKMI Cirebon",
      "startDate": "2026-09-09T00:00:00.000Z",
      "endDate": "2026-09-09T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_045_warlit",
      "programId": "prog_kaj_warlit",
      "title": "Warlit",
      "description": "Agenda Warlit dari KAJ.",
      "location": "IKMI Cirebon",
      "startDate": "2026-09-10T00:00:00.000Z",
      "endDate": "2026-09-10T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_046_reang",
      "programId": "prog_psda_reang",
      "title": "REANG",
      "description": "Agenda REANG dari PSDA.",
      "location": "IKMI Cirebon",
      "startDate": "2026-09-12T00:00:00.000Z",
      "endDate": "2026-09-12T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_047_rapat_dwi",
      "programId": "prog_bph_rapat_dwi",
      "title": "Rapat Dwi",
      "description": "Agenda Rapat Dwi dari BPH.",
      "location": "IKMI Cirebon",
      "startDate": "2026-09-13T00:00:00.000Z",
      "endDate": "2026-09-13T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_048_cimanuk",
      "programId": "prog_psda_cimanuk",
      "title": "CIMANUK",
      "description": "Agenda CIMANUK dari PSDA.",
      "location": "IKMI Cirebon",
      "startDate": "2026-09-15T00:00:00.000Z",
      "endDate": "2026-09-15T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_049_podcast_ayu",
      "programId": "prog_komdigi_podcast_ayu",
      "title": "Podcast Ayu",
      "description": "Agenda Podcast Ayu dari KOMDIGI.",
      "location": "IKMI Cirebon",
      "startDate": "2026-09-19T00:00:00.000Z",
      "endDate": "2026-09-19T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_050_warlit",
      "programId": "prog_kaj_warlit",
      "title": "Warlit",
      "description": "Agenda Warlit dari KAJ.",
      "location": "IKMI Cirebon",
      "startDate": "2026-09-24T00:00:00.000Z",
      "endDate": "2026-09-24T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_051_sapa_rasa",
      "programId": "prog_kad_sapa_rasa",
      "title": "Sapa Rasa",
      "description": "Agenda Sapa Rasa dari KAD.",
      "location": "IKMI Cirebon",
      "startDate": "2026-09-25T00:00:00.000Z",
      "endDate": "2026-09-25T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_052_ekspedisi_kampus",
      "programId": "prog_kad_ekspedisi_kampus",
      "title": "Ekspedisi Kampus",
      "description": "Agenda Ekspedisi Kampus dari KAD.",
      "location": "IKMI Cirebon",
      "startDate": "2026-10-01T00:00:00.000Z",
      "endDate": "2026-10-01T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_053_sapa_rasa",
      "programId": "prog_kad_sapa_rasa",
      "title": "Sapa Rasa",
      "description": "Agenda Sapa Rasa dari KAD.",
      "location": "IKMI Cirebon",
      "startDate": "2026-10-03T00:00:00.000Z",
      "endDate": "2026-10-03T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_054_warlit",
      "programId": "prog_kaj_warlit",
      "title": "Warlit",
      "description": "Agenda Warlit dari KAJ.",
      "location": "IKMI Cirebon",
      "startDate": "2026-10-08T00:00:00.000Z",
      "endDate": "2026-10-08T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_055_prabumi",
      "programId": "prog_kad_prabumi",
      "title": "PRABUMI",
      "description": "Agenda PRABUMI dari KAD.",
      "location": "IKMI Cirebon",
      "startDate": "2026-10-09T00:00:00.000Z",
      "endDate": "2026-10-09T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_056_prabumi",
      "programId": "prog_kad_prabumi",
      "title": "PRABUMI",
      "description": "Agenda PRABUMI dari KAD.",
      "location": "IKMI Cirebon",
      "startDate": "2026-10-10T00:00:00.000Z",
      "endDate": "2026-10-10T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_057_prabumi",
      "programId": "prog_kad_prabumi",
      "title": "PRABUMI",
      "description": "Agenda PRABUMI dari KAD.",
      "location": "IKMI Cirebon",
      "startDate": "2026-10-11T00:00:00.000Z",
      "endDate": "2026-10-11T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_058_baskara",
      "programId": "prog_psda_baskara",
      "title": "BASKARA",
      "description": "Agenda BASKARA dari PSDA.",
      "location": "IKMI Cirebon",
      "startDate": "2026-10-16T00:00:00.000Z",
      "endDate": "2026-10-16T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_059_rapat_evaluasi",
      "programId": "prog_bph_rapat_evaluasi",
      "title": "Rapat Evaluasi",
      "description": "Agenda Rapat Evaluasi dari BPH.",
      "location": "IKMI Cirebon",
      "startDate": "2026-10-17T00:00:00.000Z",
      "endDate": "2026-10-17T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_060_warlit",
      "programId": "prog_kaj_warlit",
      "title": "Warlit",
      "description": "Agenda Warlit dari KAJ.",
      "location": "IKMI Cirebon",
      "startDate": "2026-10-22T00:00:00.000Z",
      "endDate": "2026-10-22T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_061_reang",
      "programId": "prog_psda_reang",
      "title": "REANG",
      "description": "Agenda REANG dari PSDA.",
      "location": "IKMI Cirebon",
      "startDate": "2026-10-31T00:00:00.000Z",
      "endDate": "2026-10-31T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_062_baskara",
      "programId": "prog_psda_baskara",
      "title": "BASKARA",
      "description": "Agenda BASKARA dari PSDA.",
      "location": "IKMI Cirebon",
      "startDate": "2026-11-06T00:00:00.000Z",
      "endDate": "2026-11-06T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_063_sapa_rasa",
      "programId": "prog_kad_sapa_rasa",
      "title": "Sapa Rasa",
      "description": "Agenda Sapa Rasa dari KAD.",
      "location": "IKMI Cirebon",
      "startDate": "2026-11-07T00:00:00.000Z",
      "endDate": "2026-11-07T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_064_warlit",
      "programId": "prog_kaj_warlit",
      "title": "Warlit",
      "description": "Agenda Warlit dari KAJ.",
      "location": "IKMI Cirebon",
      "startDate": "2026-11-12T00:00:00.000Z",
      "endDate": "2026-11-12T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_065_makrab",
      "programId": "prog_kad_makrab",
      "title": "MAKRAB",
      "description": "Agenda MAKRAB dari KAD.",
      "location": "IKMI Cirebon",
      "startDate": "2026-11-14T00:00:00.000Z",
      "endDate": "2026-11-14T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_066_makrab",
      "programId": "prog_kad_makrab",
      "title": "MAKRAB",
      "description": "Agenda MAKRAB dari KAD.",
      "location": "IKMI Cirebon",
      "startDate": "2026-11-15T00:00:00.000Z",
      "endDate": "2026-11-15T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_067_ikmi_peduli",
      "programId": "prog_hpm_ikmi_peduli",
      "title": "IKMI PEDULI",
      "description": "Agenda IKMI PEDULI dari HPM.",
      "location": "IKMI Cirebon",
      "startDate": "2026-11-24T00:00:00.000Z",
      "endDate": "2026-11-24T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_068_warlit",
      "programId": "prog_kaj_warlit",
      "title": "Warlit",
      "description": "Agenda Warlit dari KAJ.",
      "location": "IKMI Cirebon",
      "startDate": "2026-11-26T00:00:00.000Z",
      "endDate": "2026-11-26T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_069_reang",
      "programId": "prog_psda_reang",
      "title": "REANG",
      "description": "Agenda REANG dari PSDA.",
      "location": "IKMI Cirebon",
      "startDate": "2026-11-28T00:00:00.000Z",
      "endDate": "2026-11-28T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_070_sospen",
      "programId": "prog_hpm_sospen",
      "title": "SOSPEN",
      "description": "Agenda SOSPEN dari HPM.",
      "location": "IKMI Cirebon",
      "startDate": "2026-12-03T00:00:00.000Z",
      "endDate": "2026-12-03T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_071_podcast_ayu",
      "programId": "prog_komdigi_podcast_ayu",
      "title": "Podcast Ayu",
      "description": "Agenda Podcast Ayu dari KOMDIGI.",
      "location": "IKMI Cirebon",
      "startDate": "2026-12-06T00:00:00.000Z",
      "endDate": "2026-12-06T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_072_ikmi_dugawe",
      "programId": "prog_hpm_ikmi_dugawe",
      "title": "IKMI Dugawe",
      "description": "Agenda IKMI Dugawe dari HPM.",
      "location": "IKMI Cirebon",
      "startDate": "2026-12-15T00:00:00.000Z",
      "endDate": "2026-12-15T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_073_diskusi_panel",
      "programId": "prog_kaj_diskusi_panel",
      "title": "Diskusi Panel",
      "description": "Agenda Diskusi Panel dari KAJ.",
      "location": "IKMI Cirebon",
      "startDate": "2026-12-16T00:00:00.000Z",
      "endDate": "2026-12-16T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_074_ikmi_peduli",
      "programId": "prog_hpm_ikmi_peduli",
      "title": "IKMI PEDULI",
      "description": "Agenda IKMI PEDULI dari HPM.",
      "location": "IKMI Cirebon",
      "startDate": "2026-12-17T00:00:00.000Z",
      "endDate": "2026-12-17T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_075_rapat_evaluasi",
      "programId": "prog_bph_rapat_evaluasi",
      "title": "Rapat Evaluasi",
      "description": "Agenda Rapat Evaluasi dari BPH.",
      "location": "IKMI Cirebon",
      "startDate": "2026-12-25T00:00:00.000Z",
      "endDate": "2026-12-25T02:00:00.000Z",
      "status": "UPCOMING"
    },
    {
      "id": "event_076_reang",
      "programId": "prog_psda_reang",
      "title": "REANG",
      "description": "Agenda REANG dari PSDA.",
      "location": "IKMI Cirebon",
      "startDate": "2026-12-26T00:00:00.000Z",
      "endDate": "2026-12-26T02:00:00.000Z",
      "status": "UPCOMING"
    }
  ],
  "contentPlans": [
    {
      "id": "content_001_tahun_baru_masehi",
      "title": "Hari Penting: Tahun Baru Masehi",
      "platform": "Instagram",
      "publishDate": "2026-01-01T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_002_hari_amal_bhakti_kementerian_agama",
      "title": "Hari Penting: Hari Amal Bhakti Kementerian Agama",
      "platform": "Instagram",
      "publishDate": "2026-01-03T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_003_hari_korps_wanita_angkatan_laut",
      "title": "Hari Penting: Hari Korps Wanita Angkatan Laut",
      "platform": "Instagram",
      "publishDate": "2026-01-05T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_004_hari_gerakan_satu_juta_pohon",
      "title": "Hari Penting: Hari Gerakan Satu Juta Pohon",
      "platform": "Instagram",
      "publishDate": "2026-01-10T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_005_azzumardi_azra",
      "title": "Ulang Tahun Pengurus: Azzumardi Azra",
      "platform": "Instagram",
      "publishDate": "2026-01-13T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Ketua Departemen Kajian dan Advokasi"
    },
    {
      "id": "content_006_hari_dharma_samudera",
      "title": "Hari Penting: Hari Dharma Samudera",
      "platform": "Instagram",
      "publishDate": "2026-01-15T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_007_hari_gizi_nasional",
      "title": "Hari Penting: Hari Gizi Nasional",
      "platform": "Instagram",
      "publishDate": "2026-01-25T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_008_hari_ulang_tahun_hmi",
      "title": "Hari Penting: Hari Ulang Tahun HMI",
      "platform": "Instagram",
      "publishDate": "2026-02-05T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_009_hari_pers_nasional",
      "title": "Hari Penting: Hari Pers Nasional",
      "platform": "Instagram",
      "publishDate": "2026-02-09T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_010_hari_valentine",
      "title": "Hari Penting: Hari Valentine",
      "platform": "Instagram",
      "publishDate": "2026-02-14T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_011_hari_keadilan_sosial_sedunia",
      "title": "Hari Penting: Hari Keadilan Sosial Sedunia",
      "platform": "Instagram",
      "publishDate": "2026-02-20T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_012_hari_bahasa_ibu_internasional",
      "title": "Hari Penting: Hari Bahasa Ibu Internasional",
      "platform": "Instagram",
      "publishDate": "2026-02-21T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_013_farrah_rizka_rena_fadillah",
      "title": "Ulang Tahun Pengurus: Farrah Rizka Rena Fadillah",
      "platform": "Instagram",
      "publishDate": "2026-02-27T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Anggota Ekonomi Kreatif"
    },
    {
      "id": "content_014_hari_kehakiman_nasional",
      "title": "Hari Penting: Hari Kehakiman Nasional",
      "platform": "Instagram",
      "publishDate": "2026-03-01T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_015_soliha",
      "title": "Ulang Tahun Pengurus: Soliha",
      "platform": "Instagram",
      "publishDate": "2026-03-08T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Sekretaris Umum I"
    },
    {
      "id": "content_016_hari_perempuan_internasional",
      "title": "Hari Penting: Hari Perempuan Internasional",
      "platform": "Instagram",
      "publishDate": "2026-03-08T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_017_marcel_nur_mu_ijj",
      "title": "Ulang Tahun Pengurus: Marcel Nur Mu'ijj",
      "platform": "Instagram",
      "publishDate": "2026-03-09T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Anggota Departemen HPM"
    },
    {
      "id": "content_018_galih_satria_bontot",
      "title": "Ulang Tahun Pengurus: Galih Satria Bontot",
      "platform": "Instagram",
      "publishDate": "2026-03-12T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Anggota Departemen Kajian dan Advokasi"
    },
    {
      "id": "content_019_muhammad_muzaki",
      "title": "Ulang Tahun Pengurus: Muhammad Muzaki",
      "platform": "Instagram",
      "publishDate": "2026-03-17T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Ketua Departemen Ekonomi Kreatif"
    },
    {
      "id": "content_020_ahmad_syahid",
      "title": "Ulang Tahun Pengurus: Ahmad Syahid",
      "platform": "Instagram",
      "publishDate": "2026-03-18T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Ketua Departemen PSDA"
    },
    {
      "id": "content_021_naofal_william_atalah",
      "title": "Ulang Tahun Pengurus: Naofal William Atalah",
      "platform": "Instagram",
      "publishDate": "2026-03-19T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Anggota Departemen Komdigi"
    },
    {
      "id": "content_022_safitriani_syaroni",
      "title": "Ulang Tahun Pengurus: Safitriani Syaroni",
      "platform": "Instagram",
      "publishDate": "2026-03-19T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Anggota Departemen Komdigi"
    },
    {
      "id": "content_023_hari_down_syndrome_sedunia",
      "title": "Hari Penting: Hari Down Syndrome Sedunia",
      "platform": "Instagram",
      "publishDate": "2026-03-21T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_024_derli_yanah",
      "title": "Ulang Tahun Pengurus: Derli Yanah",
      "platform": "Instagram",
      "publishDate": "2026-03-22T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Sekretaris Departemen Kaderisasi"
    },
    {
      "id": "content_025_hari_air_sedunia",
      "title": "Hari Penting: Hari Air Sedunia",
      "platform": "Instagram",
      "publishDate": "2026-03-22T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_026_hari_meteorologi_dunia",
      "title": "Hari Penting: Hari Meteorologi Dunia",
      "platform": "Instagram",
      "publishDate": "2026-03-23T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_027_very_kurniawan",
      "title": "Ulang Tahun Pengurus: Very Kurniawan",
      "platform": "Instagram",
      "publishDate": "2026-03-25T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Anggota Departemen HPM"
    },
    {
      "id": "content_028_raden_hafidz_rahmatullah",
      "title": "Ulang Tahun Pengurus: Raden Hafidz Rahmatullah",
      "platform": "Instagram",
      "publishDate": "2026-03-26T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Ketua Umum"
    },
    {
      "id": "content_029_mochammad_naufal_hilmy",
      "title": "Ulang Tahun Pengurus: Mochammad Naufal Hilmy",
      "platform": "Instagram",
      "publishDate": "2026-04-02T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Ketua Departemen Kaderisasi"
    },
    {
      "id": "content_030_hari_autisme_sedunia",
      "title": "Hari Penting: Hari Autisme Sedunia",
      "platform": "Instagram",
      "publishDate": "2026-04-02T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_031_amara_dilla_dia_dina",
      "title": "Ulang Tahun Pengurus: Amara Dilla Dia Dina",
      "platform": "Instagram",
      "publishDate": "2026-04-03T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Sekretaris Departemen Kajian dan Advokasi"
    },
    {
      "id": "content_032_hari_kesehatan_sedunia",
      "title": "Hari Penting: Hari Kesehatan Sedunia",
      "platform": "Instagram",
      "publishDate": "2026-04-07T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_033_uswatun_hasanah",
      "title": "Ulang Tahun Pengurus: Uswatun Hasanah",
      "platform": "Instagram",
      "publishDate": "2026-04-16T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Bendahara Umum II"
    },
    {
      "id": "content_034_sholelil_ulka_ababiluna",
      "title": "Ulang Tahun Pengurus: Sholelil Ulka Ababiluna",
      "platform": "Instagram",
      "publishDate": "2026-04-19T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Anggota Departemen Kajian dan Advokasi"
    },
    {
      "id": "content_035_hari_kartini",
      "title": "Hari Penting: Hari Kartini",
      "platform": "Instagram",
      "publishDate": "2026-04-21T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_036_hari_bumi",
      "title": "Hari Penting: Hari Bumi",
      "platform": "Instagram",
      "publishDate": "2026-04-22T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_037_hari_buku_sedunia",
      "title": "Hari Penting: Hari Buku Sedunia",
      "platform": "Instagram",
      "publishDate": "2026-04-23T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_038_hari_buruh_internasional",
      "title": "Hari Penting: Hari Buruh Internasional",
      "platform": "Instagram",
      "publishDate": "2026-05-01T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_039_hari_pendidikan_nasional",
      "title": "Hari Penting: Hari Pendidikan Nasional",
      "platform": "Instagram",
      "publishDate": "2026-05-02T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_040_hari_bidan_internasional",
      "title": "Hari Penting: Hari Bidan Internasional",
      "platform": "Instagram",
      "publishDate": "2026-05-05T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_041_atinah",
      "title": "Ulang Tahun Pengurus: Atinah",
      "platform": "Instagram",
      "publishDate": "2026-05-14T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Sekretaris Umum II"
    },
    {
      "id": "content_042_siti_fatimah",
      "title": "Ulang Tahun Pengurus: Siti Fatimah",
      "platform": "Instagram",
      "publishDate": "2026-05-16T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Sekretaris Departemen Komdigi"
    },
    {
      "id": "content_043_hari_buku_nasional",
      "title": "Hari Penting: Hari Buku Nasional",
      "platform": "Instagram",
      "publishDate": "2026-05-17T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_044_hari_kebangkitan_nasional",
      "title": "Hari Penting: Hari Kebangkitan Nasional",
      "platform": "Instagram",
      "publishDate": "2026-05-20T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_045_siti_rohmawati",
      "title": "Ulang Tahun Pengurus: Siti Rohmawati",
      "platform": "Instagram",
      "publishDate": "2026-05-25T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Anggota Departemen Komdigi"
    },
    {
      "id": "content_046_haidar_rasyikh_mubarok",
      "title": "Ulang Tahun Pengurus: Haidar Rasyikh Mubarok",
      "platform": "Instagram",
      "publishDate": "2026-05-28T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Sekretaris Departemen PSDA"
    },
    {
      "id": "content_047_hari_lahir_pancasila",
      "title": "Hari Penting: Hari Lahir Pancasila",
      "platform": "Instagram",
      "publishDate": "2026-06-01T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_048_hari_lingkungan_hidup_sedunia",
      "title": "Hari Penting: Hari Lingkungan Hidup Sedunia",
      "platform": "Instagram",
      "publishDate": "2026-06-05T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_049_hari_penanggulangan_desertifikasi",
      "title": "Hari Penting: Hari Penanggulangan Desertifikasi",
      "platform": "Instagram",
      "publishDate": "2026-06-17T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_050_hari_musik_dunia",
      "title": "Hari Penting: Hari Musik Dunia",
      "platform": "Instagram",
      "publishDate": "2026-06-21T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_051_danu_pratama",
      "title": "Ulang Tahun Pengurus: Danu Pratama",
      "platform": "Instagram",
      "publishDate": "2026-06-29T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Anggota Departemen HPM"
    },
    {
      "id": "content_052_hari_bhayangkara",
      "title": "Hari Penting: Hari Bhayangkara",
      "platform": "Instagram",
      "publishDate": "2026-07-01T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_053_hallimatul_syahdiyah",
      "title": "Ulang Tahun Pengurus: Hallimatul Syahdiyah",
      "platform": "Instagram",
      "publishDate": "2026-07-07T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Bendahara Umum I"
    },
    {
      "id": "content_054_hari_pustakawan",
      "title": "Hari Penting: Hari Pustakawan",
      "platform": "Instagram",
      "publishDate": "2026-07-07T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_055_hari_anak_nasional",
      "title": "Hari Penting: Hari Anak Nasional",
      "platform": "Instagram",
      "publishDate": "2026-07-23T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_056_hari_veteran_nasional",
      "title": "Hari Penting: Hari Veteran Nasional",
      "platform": "Instagram",
      "publishDate": "2026-08-10T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_057_hari_pramuka",
      "title": "Hari Penting: Hari Pramuka",
      "platform": "Instagram",
      "publishDate": "2026-08-14T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_058_hari_kemerdekaan_indonesia",
      "title": "Hari Penting: Hari Kemerdekaan Indonesia",
      "platform": "Instagram",
      "publishDate": "2026-08-17T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_059_hari_konstitusi",
      "title": "Hari Penting: Hari Konstitusi",
      "platform": "Instagram",
      "publishDate": "2026-08-18T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_060_muhamad_walid",
      "title": "Ulang Tahun Pengurus: Muhamad Walid",
      "platform": "Instagram",
      "publishDate": "2026-08-23T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Wakil Ketua Umum"
    },
    {
      "id": "content_061_faiz_ubaidilah_fazri",
      "title": "Ulang Tahun Pengurus: Faiz Ubaidilah Fazri",
      "platform": "Instagram",
      "publishDate": "2026-09-03T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Ketua Departemen HPM"
    },
    {
      "id": "content_062_hari_aksara_internasional",
      "title": "Hari Penting: Hari Aksara Internasional",
      "platform": "Instagram",
      "publishDate": "2026-09-08T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_063_hari_perhubungan_nasional",
      "title": "Hari Penting: Hari Perhubungan Nasional",
      "platform": "Instagram",
      "publishDate": "2026-09-17T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_064_hari_perdamaian_internasional",
      "title": "Hari Penting: Hari Perdamaian Internasional",
      "platform": "Instagram",
      "publishDate": "2026-09-21T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_065_hari_tani_nasional",
      "title": "Hari Penting: Hari Tani Nasional",
      "platform": "Instagram",
      "publishDate": "2026-09-28T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_066_hari_kesaktian_pancasila",
      "title": "Hari Penting: Hari Kesaktian Pancasila",
      "platform": "Instagram",
      "publishDate": "2026-10-01T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_067_rifqi_ramadhani",
      "title": "Ulang Tahun Pengurus: Rifqi Ramadhani",
      "platform": "Instagram",
      "publishDate": "2026-10-03T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Anggota Departemen PSDA"
    },
    {
      "id": "content_068_hari_tni",
      "title": "Hari Penting: Hari TNI",
      "platform": "Instagram",
      "publishDate": "2026-10-05T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_069_hari_pangan_sedunia",
      "title": "Hari Penting: Hari Pangan Sedunia",
      "platform": "Instagram",
      "publishDate": "2026-10-16T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_070_abdul_hasib",
      "title": "Ulang Tahun Pengurus: Abdul Hasib",
      "platform": "Instagram",
      "publishDate": "2026-10-25T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Sekretaris Departemen HPM"
    },
    {
      "id": "content_071_hari_sumpah_pemuda",
      "title": "Hari Penting: Hari Sumpah Pemuda",
      "platform": "Instagram",
      "publishDate": "2026-10-28T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_072_muhammad_abdul_aziz",
      "title": "Ulang Tahun Pengurus: Muhammad Abdul Aziz",
      "platform": "Instagram",
      "publishDate": "2026-11-08T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Anggota Departemen Kajian dan Advokasi"
    },
    {
      "id": "content_073_hari_pahlawan",
      "title": "Hari Penting: Hari Pahlawan",
      "platform": "Instagram",
      "publishDate": "2026-11-10T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_074_hari_kesehatan_nasional",
      "title": "Hari Penting: Hari Kesehatan Nasional",
      "platform": "Instagram",
      "publishDate": "2026-11-12T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_075_reisya_kamalia_ihsana",
      "title": "Ulang Tahun Pengurus: Reisya Kamalia Ihsana",
      "platform": "Instagram",
      "publishDate": "2026-11-16T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Sekretaris Departemen Ekonomi Kreatif"
    },
    {
      "id": "content_076_akhmad_yani",
      "title": "Ulang Tahun Pengurus: Akhmad Yani",
      "platform": "Instagram",
      "publishDate": "2026-11-19T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Anggota Departemen PDDS"
    },
    {
      "id": "content_077_hari_guru_nasional",
      "title": "Hari Penting: Hari Guru Nasional",
      "platform": "Instagram",
      "publishDate": "2026-11-25T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_078_riza_alraihany",
      "title": "Ulang Tahun Pengurus: Riza Alraihany",
      "platform": "Instagram",
      "publishDate": "2026-11-30T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Ketua Departemen Komdigi"
    },
    {
      "id": "content_079_hari_aids_sedunia",
      "title": "Hari Penting: Hari AIDS Sedunia",
      "platform": "Instagram",
      "publishDate": "2026-12-01T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_080_hari_disabilitas_internasional",
      "title": "Hari Penting: Hari Disabilitas Internasional",
      "platform": "Instagram",
      "publishDate": "2026-12-03T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_081_hari_anti_korupsi_sedunia",
      "title": "Hari Penting: Hari Anti Korupsi Sedunia",
      "platform": "Instagram",
      "publishDate": "2026-12-09T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_082_hari_ham_sedunia",
      "title": "Hari Penting: Hari HAM Sedunia",
      "platform": "Instagram",
      "publishDate": "2026-12-10T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_083_sulthon_azizan_zanuar",
      "title": "Ulang Tahun Pengurus: Sulthon Azizan Zanuar",
      "platform": "Instagram",
      "publishDate": "2026-12-22T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Ulang Tahun Pengurus",
      "relatedPosition": "Anggota Departemen Kaderisasi"
    },
    {
      "id": "content_084_hari_ibu",
      "title": "Hari Penting: Hari Ibu",
      "platform": "Instagram",
      "publishDate": "2026-12-22T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    },
    {
      "id": "content_085_hari_natal",
      "title": "Hari Penting: Hari Natal",
      "platform": "Instagram",
      "publishDate": "2026-12-25T00:00:00.000Z",
      "status": "PLANNED",
      "category": "Hari Penting",
      "relatedPosition": "-"
    }
  ]
} as const
