---
config:
  layout: elk
---
flowchart TD
  KETUA[Ketua Umum]
  WAKIL[Wakil Ketua Umum]
  SEK1[Sekretaris Umum I]
  SEK2[Sekretaris Umum II]
  BEN1[Bendahara Umum I]
  BEN2[Bendahara Umum II]

  KETUA --> WAKIL
  WAKIL --> SEK1
  WAKIL --> SEK2
  WAKIL --> BEN1
  WAKIL --> BEN2

  subgraph DEPARTEMEN["Departemen"]
    DKAD[Departemen Kaderisasi]
    DKAJ[Departemen Advokasi & Kajian Strategis]
    DPSDA["Departemen Pengembangan Sumber Daya Anggota (PSDA)"]
    DEKRAF["Departemen Ekonomi Kreatif (Ekraf)"]
    DKOMDIGI["Departemen Komunikasi & Digitalisasi (Komdigi)"]
    DHPM["Departemen Hubungan & Pengabdian Masyarakat (HPM)"]
  end

  WAKIL --> DEPARTEMEN

  classDef leader stroke:#a78bfa,fill:#f5f3ff
  classDef depart stroke:#4ade80,fill:#f0fdf4

  class KETUA,WAKIL,SEK1,SEK2,BEN1,BEN2 leader
  class DKAD,DKAJ,DPSDA,DEKRAF,DKOMDIGI,DHPM depart