---
config:
  layout: elk
---
%% =====================================================
%% 2. Membership Lifecycle
%% =====================================================
flowchart TD
  CA[Calon Anggota]
  RV[Review]
  PRB[PRABUMI]
  MKR[MAKRAB]
  AKT[Anggota Aktif]
  PNG[Pengurus]
  DEM[Demisioner]
  ALU[Alumni]

  CA --> RV --> PRB --> MKR --> AKT --> PNG --> DEM --> ALU

  classDef stage stroke:#38bdf8,fill:#f0f9ff
  class CA,RV,PRB,MKR,AKT,PNG,DEM,ALU stage